version: '3.9'

services:

  cms:
    image: backstore
    pull_policy: never
    build:
      context: ./backstore
      # see exportUserAndGroupIds.sh
      args:
        - USER_ID
        - GROUP_ID
    restart: always
    ports:
      - 8000:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $CMS_DB_USER
      WORDPRESS_DB_PASSWORD: $CMS_DB_PASSWORD
      WORDPRESS_DB_NAME: $CMS_DB_NAME
      WORDPRESS_CONFIG_EXTRA: |
        define('SITE_HOST',
            '' === getenv('CODESPACE_NAME') ?
              'http://localhost:8000' :
              "https://".getenv('CODESPACE_NAME')."-8000.".getenv('GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN')
        );
        define('WP_HOME', SITE_HOST);
        define('WP_SITEURL', SITE_HOST);
    volumes:
      - ./backstore/wordpress:/var/www/html
      - ./backstore/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro

  db:
    image: mariadb
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $CMS_DB_NAME
      MYSQL_USER: $CMS_DB_USER
      MYSQL_PASSWORD: $CMS_DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
