#!/usr/bin/env bash
cat > .env <<EOF
USER_ID=$(id -u)
GROUP_ID=$(id -g)

CODESPACE_NAME=$CODESPACE_NAME
GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN=$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN

CMS_DB_NAME=aixmazon
CMS_DB_USER=dbuser
CMS_DB_PASSWORD=dbpassword
EOF
